name: Backend-CICD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.11.7
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          apt-get update && apt-get install --no-install-recommends -y python3.8-dev python3-setuptools default-libmysqlclient-dev build-essential
          pip install -r src/requirements.txt
      - name: run django test
        run: |
          python src/manage.py test
  
  build:
    runs-on: ubuntu-latest
    container: docker:20.10.24
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t yoyo200181/smcs:v1.0 .
          docker push yoyo200181/smcs:v1.0
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.SERVER_PORT}}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSHKEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull yoyo200181/smcs:v1.0
            cd ${{ secrets.SERVER_PROJECT_PATH}}
            docker-compose up -d