version: '3.9'
services:
  api:
    image: yoyo200181/smcs:v1.0
    ports:
      - "8000:8000"
    env_file:
      - ${ENV_FILE:-.env.local}  # Defaults to .env.local
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app
  
  db:
    image: mysql:9
    env_file:
      - ${ENV_FILE:-.env.local}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-smcs}
      MYSQL_USER: ${MYSQL_USER:-yoyo}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Yoyo_200181}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Yoyo_200181}
      MYSQL_HOST: ${MYSQL_HOST:-db}
      MYSQL_PORT: ${MYSQL_PORT:-3306}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  # db:
  #   image: mysql:9.0
  #   environment:
  #     MYSQL_DATABASE: railway
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: password
  #     MYSQL_ROOT_PASSWORD: rJOsmKbBRsjuZkzWmnFJnKjWwORCBcdS
  #     MYSQL_HOST: tramway.proxy.rlwy.net
  #     MYSQL_PORT: 59626
  #   volumes:
  #     - db-data:/var/lib/mysql

volumes:
  db-data: