version: '3.9'
services:
  server:
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=87c7e33518d2fef1fb200e2ff34579362a3e5bad3bcb8aa1
      - DEBUG=True
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./src:/app
    # networks:
    #   - app-network
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rJOsmKbBRsjuZkzWmnFJnKjWwORCBcdS
      MYSQL_HOST: tramway.proxy.rlwy.net
      MYSQL_PORT: 59626
    volumes:
      - db-data:/var/lib/mysql
    # networks:
    #   - app-network
volumes:
  db-data:

networks:
  default:

# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

