version: '3.9'
services:
  api:
    image: yoyo200181/smcs:v1.0
    ports:
      - "8000:8000"
    env_file:
      - ${ENV_FILE:-.env.local}  # Defaults to .env.local
    environment:
      - SECRET_KEY=87c7e33518d2fef1fb200e2ff34579362a3e5bad3bcb8aa1
      - DEBUG=True
    depends_on:
      - db
    volumes:
      - ./src:/app
  # server:
  #   build:
  #     context: ./src
  #     dockerfile: Dockerfile
  #   environment:
  #     - SECRET_KEY=87c7e33518d2fef1fb200e2ff34579362a3e5bad3bcb8aa1
  #     - DEBUG=True
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./src:/app
  
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-smcs}
      MYSQL_USER: ${MYSQL_DATABASE:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:--Yoyo200181}
      MYSQL_HOST: ${MYSQL_HOST:-localhost}
      MYSQL_PORT: ${MYSQL_PORT:-3306}
    volumes:
      - db-data:/var/lib/mysql

  # db:
  #   image: mysql:9.0
  #   environment:
  #     MYSQL_DATABASE: railway
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: password
  #     MYSQL_ROOT_PASSWORD: rJOsmKbBRsjuZkzWmnFJnKjWwORCBcdS
  #     MYSQL_HOST: tramway.proxy.rlwy.net
  #     MYSQL_PORT: 59626
  #   volumes:
  #     - db-data:/var/lib/mysql

volumes:
  db-data: