# Generated by Django 5.2.1 on 2025-05-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kcal', models.IntegerField()),
                ('protein', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fat', models.DecimalField(decimal_places=1, max_digits=3)),
                ('carbs', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fiber', models.DecimalField(decimal_places=1, max_digits=3)),
                ('salt', models.DecimalField(decimal_places=1, max_digits=3)),
                ('image_url', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('type', models.CharField(choices=[
                    ('MEAT', 'meat'),
                    ('EGG', 'egg'),
                    ('VEGETABLE', 'vegetable'),
                    ('GRAIN', 'grain'), ('SET', 'set')], default='MEAT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
