# Generated by Django 5.2.1 on 2025-05-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserManager',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('password',
                 models.CharField(
                     max_length=128,
                     verbose_name='password')),
                ('last_login',
                 models.DateTimeField(
                     blank=True,
                     null=True,
                     verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
