name: Backend-CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        run: flake8

  test:
    runs-on: ubuntu-latest
    services:
    mysql:
      image: mysql:9
      env:
        MYSQL_DATABASE: smcs
        MYSQL_USER: yoyo
        MYSQL_PASSWORD: Yoyo_200181
        MYSQL_ROOT_PASSWORD: Yoyo_200181
      ports:
          - 3306:3306
      options: >
        --health-cmd="mysqladmin ping"
        --health-interval=10s
        --health-timeout=5s
        --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: install dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
            gcc \
            python3-dev \
            pkg-config \
            libmariadb-dev-compat \
            libmariadb-dev \
            build-essential
          pip install -r src/requirements.txt
      - name: run django test
        env:
          MYSQL_DATABASE: smcs
          MYSQL_USER: yoyo
          MYSQL_PASSWORD: Yoyo_200181
          MYSQL_HOST: mysql
          MYSQL_PORT: 3306
          SECRET_KEY: 87c7e33518d2fef1fb200e2ff34579362a3e5bad3bcb8aa1
          DEBUG: True
        run: |
          python src/manage.py test
  
  build:
    runs-on: ubuntu-latest
    container: docker:20.10.24
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t yoyo200181/smcs:v1.0 .
          docker push yoyo200181/smcs:v1.0
  
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: deploy
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         port: ${{ secrets.SERVER_PORT}}
  #         username: ${{ secrets.SERVER_USERNAME }}
  #         key: ${{ secrets.SERVER_SSHKEY }}
  #         script: |
  #           docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
  #           docker pull yoyo200181/smcs:v1.0
  #           cd ${{ secrets.SERVER_PROJECT_PATH}}
  #           docker-compose up -d